### ISSUE TITLE
Do you mind if I delete the utility from the Python repo?

### ISSUE THREAD

**Issue by gvanrossum** [ilevkivskyi/com2ann#1]
I expect that the copy of this utility in the core Python repo is very soon going to be out of date and forgotten. I propose to delete it from there so we don't have to deal with well-meaning core devs making uncoordinated changes there.

**Comment by ilevkivskyi** [comment]
@gvanrossum  OK, go ahead, let us move development here.

**Comment by ilevkivskyi** [comment]
@gvanrossum By the way I opened an issue for this http://bugs.python.org/issue28038

So that as soon as you do it, you could also close the issue on b.p.o.

**Comment by gvanrossum** [comment]
Done!
