### ISSUE TITLE
Transformation of typed class factories breaks the code

### ISSUE THREAD

**Issue by jugmac00** [ilevkivskyi/com2ann#30]
Given...

```
from typing import Optional
from typing import List

class Pizza:
    def __init__(self, ingredients=None):
        # type: (Optional[List[str]]) -> None
        if ingredients is None:
            self.ingredients = []
        else:
            self.ingredients = ingredients

    def __repr__(self):
        # type: () -> str
        return "This is a Pizza with %s on it" % " ".join(self.ingredients)

    @classmethod
    def pizza_salami(cls):
        # type: () -> Pizza
        return cls(ingredients=["Salami", "Cheese", "Onions"])
```

... using `com2ann factory.py`, I receive the following code ...

```
from typing import Optional
from typing import List

class Pizza:
    def __init__(self, ingredients: Optional[List[str]] = None) -> None:
        if ingredients is None:
            self.ingredients = []
        else:
            self.ingredients = ingredients

    def __repr__(self) -> str:
        return "This is a Pizza with %s on it" % " ".join(self.ingredients)

    @classmethod
    def pizza_salami(cls) -> Pizza:
        return cls(ingredients=["Salami", "Cheese", "Onions"])
```
... which is no valid Python code any more as `Pizza` is not yet defined.

Here, the fix is to add quotes around the Pizza return type in the factory method.

As I am brand new to Python typing, maybe there are some other ways to fix this problem.

Maybe this discussion is any help: https://github.com/python/typing/issues/58

**Comment by ilevkivskyi** [comment]
You can use `from __future__ import annotations`, there is actually a flag to automatically insert such imports `--add-future-imports`.

**Comment by jugmac00** [comment]
Thanks for this super quick reply.

`from __future__ import annotations` seems to require Python 3.7. The code base I am working on has to support Python 3.5 and up.

In your README you write "supports Python 3.4+" - which is technically not correct for my case? 

Is wrapping the class names with single quotes the way to go?

Thanks for your tool and your help!

**Comment by ilevkivskyi** [comment]
> Is wrapping the class names with single quotes the way to go?

Yes, you can do this manually. I am not interested in adding an automated way to add them.
