### ISSUE TITLE
Merge type annotation from typeshed

### ISSUE THREAD

**Issue by pmhahn** [ilevkivskyi/com2ann#31]
[typeshed](https://github.com/python/typeshed) already carries type annotations for many "legacy" Python modules. As they evolve it becomes harder and harder to keep them synchronized. This becomes a non-issue if the type annotation is already included with the upstream source code and thus the `typeshed` is not needed at all.
It would be cool if `com2ann` had a mode to merge the annotations from `typeshed` into the source code of the module itself.

**Comment by gvanrossum** [comment]
I believe there’s a different tool in pyrope that can do this: https://github.com/google/pytype/blob/f30a091552a0a356538ad05ed4c994a7ba62bdf5/pytype/tools/merge_pyi/README.md

Note that this doesn’t solve all problems — type-checking the newly-annotated module will usually trigger a whole lot of errors that you’d have to fix manually.
