### ISSUE TITLE
Type comment left in place when expression is type ignored

### ISSUE THREAD

**Issue by PeterJCLaw** [ilevkivskyi/com2ann#34]
Thanks for this tool, it's really useful :)

If you have code like this:
``` python
    foo = object()

    bar = (
        # Comment which explains why this ignored
        foo.quox   # type: ignore[attribute]
    )  # type: Mapping[str, Distribution]
```
Then after running `com2ann` you end up with:
``` python
    foo = object()

    bar: Mapping[str, int] = (
        # Comment which explains why this ignored
        foo.quox   # type: ignore[attribute]
    )  # type: Mapping[str, int]
```
which `mypy` then complains about due to the double signature.

The intermediate (explanatory) comment doesn't seem to be related, though the `type: ignore` comment is.

**Comment by ilevkivskyi** [comment]
Thanks, should be fixed now.
