### ISSUE TITLE
Release to PyPI?

### ISSUE THREAD

**Issue by Zac-HD** [ilevkivskyi/com2ann#38]
Hi @ilevkivskyi - I was wondering if you could release a new version on PyPI?  It would be lovely to have the `python-requires` metadata reflect actual compatibility, and the annotated-type-ignore support would also be great.

**Comment by ilevkivskyi** [comment]
Yeah, I will try to make a release this weekend.

**Comment by ilevkivskyi** [comment]
OK, I just published a release on PyPI https://pypi.org/project/com2ann/0.3.0/#files
