### ISSUE TITLE
Is the --python-minor-version used correctly ?

### ISSUE THREAD

**Issue by ewjoachim** [ilevkivskyi/com2ann#44]
I could be wrong, but following the code, whatever is put in `--python-minor-version`, as an int, is passed to `ast.parse(feature_version=<>)`.

The doc of `ast.parse` says:
> Also, setting feature_version to a tuple `(major, minor)` will attempt to parse using that Python version’s grammar. Currently major must equal to 3. For example, setting feature_version=(3, 4) will allow the use of async and await as variable names. The lowest supported version is (3, 4); the highest is `sys.version_info[0:2]`.

I think we should be doing `ast.parse(feature_version=(3, python_minor_version))`.

Can you confirm ?
Thank you !

**Comment by ilevkivskyi** [comment]
Hm, this is interesting. It looks like passing a plain it also works at least on Python 3.8. But apparently it is not an officially documented way to call it. So we should switch to the tuple probably, PRs are welcome!
