### ISSUE TITLE
Skip if type is not already imported

### ISSUE THREAD

**Issue by OscarVanL** [ilevkivskyi/com2ann#56]
I ran into a few cases where there was previously a type comment that was then switched into a type annotation, but then I get a syntax error because that thing was not previously imported.

There are a few possible solutions:
* Skip the conversion from type comments to type annotations if the type target was not found/not imported.
* Change the annotation but raise a warning if it's not imported, this way I can go back and fixup the imports how I see fit.

Maybe these two behaviours could be controlled by a flag.

**Comment by ilevkivskyi** [comment]
If it was not imported, how any of the type checkers worked with it? Anyway, I think you should use `--add-future-imports` option, it will add `from __future__ import annotations` to each file where non-trivial transformations were made. This import effectively preserves semantics of "annotation as a string".

**Comment by OscarVanL** [comment]
The type annotations were simply broken before. I am touching a legacy codebase that does not have MyPy, so much of it is incorrect. 

I will look into that option, it looks to do what I want 😃

Thanks!
